server:
  port: 8989
  servlet:
    context-path: /backgorundsystem
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.47:3306/backgroundsystem?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

mybatis:
  mapper-locations: classpath:com/tianye/mapper/*Mapper.xml

fdfs:
  tracker-list:
    - 192.168.79.138:22122
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150

